#! /usr/bin/env node
var path = require('path');
var migrations = require('./lib/migrations');
var chalk = require('chalk');

var args = process.argv.slice(2);


var command = args[0];
var database = args[1];

var migrationsPath;
if (args[2]) {
  migrationsPath = path.normalize(args[2]);

  if (!path.isAbsolute(migrationsPath)) {
    migrationsPath = path.normalize(path.join(process.cwd(), migrationsPath));
  }
}

var handlers = {
  run: function() {
    migrations(database).fromDirectory(migrationsPath).run(function(err, result) {
      if (err) {
        console.log(err);
        return process.exit(1);
      }
      printResult(result);
      process.exit();
    });
  },
  info: function() {
    migrations(database).fromDirectory(migrationsPath).info(function(err, info) {
      if (err) {
        console.log(err);
        return process.exit(1);
      }
      printInfo(info);
      process.exit();
    });
  }
};

function printResult(result) {
}

function printInfo(info) {
  console.log(chalk.magenta('Applied') + '                  | ' + chalk.magenta('Name'));

  info.applied.map(function(migration) {
    console.log(chalk.green(migration.applied.toISOString()) + ' | ' + chalk.yellow(migration.name));
  });
}

var handler = handlers[command];

if (!handler || (command === 'run' && !migrationsPath)) {
  console.log('Usage: sfm [' + Object.keys(handlers).join('|') + '] [database url] [migrations path]');
  process.exit(1);
}

handler(database);
